In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/Toyota.csv')

In [3]:
df.head()

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500,23.0,46986,Diesel,90,1.0,0,2000,three,1165
1,1,13750,23.0,72937,Diesel,90,1.0,0,2000,3,1165
2,2,13950,24.0,41711,Diesel,90,NaN,0,2000,3,1165
3,3,14950,26.0,48000,Diesel,90,0.0,0,2000,3,1165
4,4,13750,30.0,38500,Diesel,90,0.0,0,2000,3,1170

In [12]:
df = pd.read_csv('/content/Toyota.csv',index_col=0)

In [13]:
df.head()

   Price   Age     KM FuelType  HP  MetColor  Automatic    CC  Doors  Weight
0  13500  23.0  46986   Diesel  90       1.0          0  2000  three    1165
1  13750  23.0  72937   Diesel  90       1.0          0  2000      3    1165
2  13950  24.0  41711   Diesel  90       NaN          0  2000      3    1165
3  14950  26.0  48000   Diesel  90       0.0          0  2000      3    1165
4  13750  30.0  38500   Diesel  90       0.0          0  2000      3    1170

copying data


1 shallow copy #if we made changes to the copy of the data it will also affect original data


2 Deep copy  #vice versa



 data.copy(deep=True)

In [14]:
df.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435],
      dtype='int64', length=1436)

In [15]:
df.columns

Index(['Price', 'Age', 'KM', 'FuelType', 'HP', 'MetColor', 'Automatic', 'CC',
       'Doors', 'Weight'],
      dtype='object')

In [16]:
df.size

14360

In [17]:
df.shape

(1436, 10)

In [20]:
df.memory_usage()

Index        11488
Price        11488
Age          11488
KM           11488
FuelType     11488
HP           11488
MetColor     11488
Automatic    11488
CC           11488
Doors        11488
Weight       11488
dtype: int64

In [21]:
df.ndim

2

# Indexing and selecting data

In [22]:
df.head()

   Price   Age     KM FuelType  HP  MetColor  Automatic    CC  Doors  Weight
0  13500  23.0  46986   Diesel  90       1.0          0  2000  three    1165
1  13750  23.0  72937   Diesel  90       1.0          0  2000      3    1165
2  13950  24.0  41711   Diesel  90       NaN          0  2000      3    1165
3  14950  26.0  48000   Diesel  90       0.0          0  2000      3    1165
4  13750  30.0  38500   Diesel  90       0.0          0  2000      3    1170

In [23]:
df.tail()

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
1431,7500,NaN,20544,Petrol,86,1.0,0,1300,3,1025
1432,10845,72.0,??,Petrol,86,0.0,0,1300,3,1015
1433,8500,NaN,17016,Petrol,86,0.0,0,1300,3,1015
1434,7250,70.0,??,NaN,86,1.0,0,1300,3,1015
1435,6950,76.0,1,Petrol,110,0.0,0,1600,5,1114

In [25]:
df.at[5,"KM"]  #5th row at km column

'61000'

In [27]:
df.iat[2,3]

'Diesel'

In [28]:
df.loc[:,"FuelType"]

0       Diesel
1       Diesel
2       Diesel
3       Diesel
4       Diesel
         ...
1431    Petrol
1432    Petrol
1433    Petrol
1434       NaN
1435    Petrol
Name: FuelType, Length: 1436, dtype: object