In [50]:
import pandas as pd

In [53]:
data = pd.read_csv("/content/Toyota.csv",index_col=0)

In [14]:
data.head()

   Price   Age     KM FuelType  HP  MetColor  Automatic    CC  Doors  Weight
0  13500  23.0  46986   Diesel  90       1.0          0  2000  three    1165
1  13750  23.0  72937   Diesel  90       1.0          0  2000      3    1165
2  13950  24.0  41711   Diesel  90       NaN          0  2000      3    1165
3  14950  26.0  48000   Diesel  90       0.0          0  2000      3    1165
4  13750  30.0  38500   Diesel  90       0.0          0  2000      3    1170

Data types :-

1 Numeric : float64 & integer64

2  charecters :  category & object64

In [15]:
data.dtypes

Price          int64
Age          float64
KM            object
FuelType      object
HP            object
MetColor     float64
Automatic      int64
CC             int64
Doors         object
Weight         int64
dtype: object

# Unique

In [16]:
df = pd.DataFrame(data)

In [26]:
df.dtypes.value_counts()  #return unique dtypes

int64      4
object     4
float64    2
Name: count, dtype: int64

# select data based on data type

In [31]:
df.select_dtypes(exclude=['object']) #we selected int & float number

      Price   Age  MetColor  Automatic    CC  Weight
0     13500  23.0       1.0          0  2000    1165
1     13750  23.0       1.0          0  2000    1165
2     13950  24.0       NaN          0  2000    1165
3     14950  26.0       0.0          0  2000    1165
4     13750  30.0       0.0          0  2000    1170
...     ...   ...       ...        ...   ...     ...
1431   7500   NaN       1.0          0  1300    1025
1432  10845  72.0       0.0          0  1300    1015
1433   8500   NaN       0.0          0  1300    1015
1434   7250  70.0       1.0          0  1300    1015
1435   6950  76.0       0.0          0  1600    1114

[1436 rows x 6 columns]

# summary

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1336 non-null   float64
 2   KM         1436 non-null   object
 3   FuelType   1336 non-null   object
 4   HP         1436 non-null   object
 5   MetColor   1286 non-null   float64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   object
 9   Weight     1436 non-null   int64
dtypes: float64(2), int64(4), object(4)
memory usage: 123.4+ KB

In [34]:
df.head(3)

   Price   Age     KM FuelType  HP  MetColor  Automatic    CC  Doors  Weight
0  13500  23.0  46986   Diesel  90       1.0          0  2000  three    1165
1  13750  23.0  72937   Diesel  90       1.0          0  2000      3    1165
2  13950  24.0  41711   Diesel  90       NaN          0  2000      3    1165

wronged data types so we should change below mentioned elements of a column to correct dtype

# km is read as object
#hp     is int
#met color float
#automatic is read as int

In [33]:
import numpy as np

In [41]:
np.unique(df["KM"])

array(['1', '10000', '100123', ..., '99865', '99971', '??'], dtype=object)

In [43]:
print(np.unique(df["KM"]))

['1' '10000' '100123' ... '99865' '99971' '??']

In [45]:
print(np.unique(df["HP"]))

['107' '110' '116' '192' '69' '71' '72' '73' '86' '90' '97' '98' '????']

In [46]:
print(np.unique(df["MetColor"]))

[ 0.  1. nan]

In [47]:
print(np.unique(df["Automatic"]))

[0 1]

In [52]:
print(np.unique(df["Doors"]))  # the reason is 5 4 3 are as object

['2' '3' '4' '5' 'five' 'four' 'three']

In [55]:
#Dealing with missing values

In [60]:
data = pd.read_csv("/content/Toyota.csv",index_col=0,na_values=["??","????"])

In [61]:
df.head()

   Price   Age     KM FuelType  HP  MetColor  Automatic    CC  Doors  Weight
0  13500  23.0  46986   Diesel  90       1.0          0  2000  three    1165
1  13750  23.0  72937   Diesel  90       1.0          0  2000      3    1165
2  13950  24.0  41711   Diesel  90       NaN          0  2000      3    1165
3  14950  26.0  48000   Diesel  90       0.0          0  2000      3    1165
4  13750  30.0  38500   Diesel  90       0.0          0  2000      3    1170

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1336 non-null   float64
 2   KM         1436 non-null   object
 3   FuelType   1336 non-null   object
 4   HP         1436 non-null   object
 5   MetColor   1286 non-null   float64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   object
 9   Weight     1436 non-null   int64
dtypes: float64(2), int64(4), object(4)
memory usage: 123.4+ KB