<a href="https://colab.research.google.com/github/swarubm/NPTL-DS/blob/main/iris%20dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import pandas as pd

In [52]:
data = pd.read_csv("/content/Iris_data_sample.csv",index_col=0)

In [51]:
data.head()

,Unnamed: 0,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,NaN,1.4,0.2,NaN
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,??,3.1,1.5,0.2,Iris-setosa
4,5,5,3.6,###,0.2,Iris-setosa

In [53]:
data = pd.read_csv("/content/Iris_data_sample.csv",index_col=0,na_values=["??"])

In [54]:
data.head()

   SepalLengthCm  SepalWidthCm PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5           1.4           0.2  Iris-setosa
2            4.9           NaN           1.4           0.2          NaN
3            4.7           3.2           1.3           0.2  Iris-setosa
4            NaN           3.1           1.5           0.2  Iris-setosa
5            5.0           3.6           ###           0.2  Iris-setosa

In [55]:
data = pd.read_csv("/content/Iris_data_sample.csv",index_col=0,na_values=["??","###"])

In [56]:
data.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           NaN            1.4           0.2          NaN
3            4.7           3.2            1.3           0.2  Iris-setosa
4            NaN           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            NaN           0.2  Iris-setosa

In [58]:
df = pd.DataFrame